name: ourESchool
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations:
  observable_ish:
  auto_size_text:
  bloc:
  bottom_navy_bar:
  cached_network_image:
  camera: ^0.5.8+5
  cloud_firestore:
  cupertino_icons:
  custom_radio_grouped_button:
  division:
  equatable:
  eva_icons_flutter:
  file_picker: ^1.12.0
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_in_app_messaging:
  firebase_messaging:
  firebase_storage: ^4.0.0
  flare_splash_screen:
  flutter_bloc:
  flutter_form_builder:
  flutter_hooks:
  flutter_local_notifications:
  flutter_plugin_pdf_viewer:
  flutter_sparkline:
  flutter_spinkit:
  flutter_staggered_grid_view:
  font_awesome_flutter:
  freezed_annotation:
  get_it:
  google_fonts:
  google_maps_flutter:
  google_sign_in:
  http:
  image:
  image_picker:
  intl:
  intro_views_flutter:
  json_annotation:
  logging:
  maps_toolkit:
  meta:
  path_provider:
  permission_handler: ^4.4.0+hotfix.2
  photo_view:
  provider:
  random_color:
  rxdart:
  shared_preferences:
  stacked:
  stacked_hooks:
  stacked_services:
  vector_math:
  framy_annotation:
  device_preview:
  auto_route:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:
  framy_generator:
  auto_route_generator:


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flare_anim/Loading.flr

  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/nunito/Customicons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/nunito/MyFlutterApp.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Black.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-Italic.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf

    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic
