name: ourESchool
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  observable_ish: ^2.1.4
  auto_size_text: ^2.1.0
  bloc: null
  bottom_navy_bar: ^5.4.0
  cached_network_image: ^2.3.1
  camera: ^0.5.8+5
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.3
  custom_radio_grouped_button: ^1.0.0
  division: ^0.8.7+2
  equatable: null
  eva_icons_flutter: ^2.0.0
  file_picker: ^1.12.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_in_app_messaging: ^0.2.0+1
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  flare_splash_screen: ^3.0.1
  flutter_bloc: null
  flutter_form_builder: ^3.14.0
  flutter_hooks: null
  flutter_local_notifications: ^3.0.0+1
  flutter_plugin_pdf_viewer: null
  flutter_sparkline: ^0.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_grid_view: ^0.3.0
  font_awesome_flutter: ^8.8.1
  freezed_annotation: null
  get_it: ^4.0.2
  google_fonts: ^1.1.0
  google_maps_flutter: null
  google_sign_in: ^4.5.4
  http: ^0.12.2
  image: ^2.1.4
  image_picker: ^0.6.7+4
  intl: ^0.16.1
  intro_views_flutter: ^2.8.1
  json_annotation: null
  logging: ^0.11.4
  maps_toolkit: null
  meta: ^1.2.3
  path_provider: ^1.6.5
  permission_handler: ^4.4.0+hotfix.2
  photo_view: ^0.9.2
  provider: ^4.1.3
  random_color: ^1.0.3
  rxdart: null
  shared_preferences: ^0.5.7+3
  stacked: ^1.7.6
  stacked_hooks: null
  stacked_services: ^0.6.0
  vector_math: null
  framy_annotation:
  device_preview:
  auto_route:



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: null
  json_serializable: null
  framy_generator:
  auto_route_generator:


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flare_anim/Loading.flr

  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/nunito/Customicons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/nunito/MyFlutterApp.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Black.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-Italic.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf

    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic
